//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangGia
    {
        public string MASP { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<int> GiaNhap { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
