//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUNHAP
    {
        public string MACTPN { get; set; }
        public string MAPN { get; set; }
        public string MASP { get; set; }
        public Nullable<int> SOLUONGNHAP { get; set; }
        public Nullable<int> GIANHAP { get; set; }
        public Nullable<int> THANHTIEN { get; set; }
        public string GHICHU { get; set; }
    
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
