//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.DATHANGs = new HashSet<DATHANG>();
            this.HOADONs = new HashSet<HOADON>();
            this.QL_NHOMND = new HashSet<QL_NHOMND>();
        }
    
        public string MANV { get; set; }
        public string TENNV { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIACHI { get; set; }
        public string GIOITINH { get; set; }
        public string SDT { get; set; }
        public string MABP { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<bool> HOATDONG { get; set; }
    
        public virtual BOPHAN BOPHAN { get; set; }
        public virtual ICollection<DATHANG> DATHANGs { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual ICollection<QL_NHOMND> QL_NHOMND { get; set; }
    }
}
