//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_NHOMND
    {
        public QL_NHOMND()
        {
            this.QL_PHANQUYEN = new HashSet<QL_PHANQUYEN>();
            this.NHANVIENs = new HashSet<NHANVIEN>();
        }
    
        public string MANHOM { get; set; }
        public string TENNHOM { get; set; }
        public string GHICHU { get; set; }
    
        public virtual ICollection<QL_PHANQUYEN> QL_PHANQUYEN { get; set; }
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
    }
}
