//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QL_PHANQUYEN
    {
        public string MANHOM { get; set; }
        public string MAMANHINH { get; set; }
        public Nullable<bool> COQUYEN { get; set; }
    
        public virtual DM_MAHINH DM_MAHINH { get; set; }
        public virtual QL_NHOMND QL_NHOMND { get; set; }
    }
}
