//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.BangGias = new HashSet<BangGia>();
            this.CT_DATHANG = new HashSet<CT_DATHANG>();
            this.CT_HOADON = new HashSet<CT_HOADON>();
            this.CT_PHIEUNHAP = new HashSet<CT_PHIEUNHAP>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> GIA { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public string MANCC { get; set; }
        public string MALOAI { get; set; }
        public string ANH { get; set; }
        public string ANHCT { get; set; }
    
        public virtual ICollection<BangGia> BangGias { get; set; }
        public virtual ICollection<CT_DATHANG> CT_DATHANG { get; set; }
        public virtual ICollection<CT_HOADON> CT_HOADON { get; set; }
        public virtual ICollection<CT_PHIEUNHAP> CT_PHIEUNHAP { get; set; }
        public virtual LOAISP LOAISP { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
