//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopThoiTrang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_ShopThoiTrangEntities4 : DbContext
    {
        public QL_ShopThoiTrangEntities4()
            : base("name=QL_ShopThoiTrangEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BangGia> BangGias { get; set; }
        public DbSet<BOPHAN> BOPHANs { get; set; }
        public DbSet<CT_DATHANG> CT_DATHANG { get; set; }
        public DbSet<CT_HOADON> CT_HOADON { get; set; }
        public DbSet<CT_PHIEUNHAP> CT_PHIEUNHAP { get; set; }
        public DbSet<DATHANG> DATHANGs { get; set; }
        public DbSet<DM_MAHINH> DM_MAHINH { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<LOAISP> LOAISPs { get; set; }
        public DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public DbSet<NHANVIEN> NHANVIENs { get; set; }
        public DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public DbSet<QL_NHOMND> QL_NHOMND { get; set; }
        public DbSet<QL_PHANQUYEN> QL_PHANQUYEN { get; set; }
        public DbSet<SANPHAM> SANPHAMs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
